# ----------------------------------------------------------------------
# Config for theme: Fresh
# ----------------------------------------------------------------------

baseurl             = "https://klueless.io"
languageCode        = "en-au"
title               = "Klueless"
theme               = "fresh"
googleAnalytics     = "UA-45288102-13"
paginate            = 12

disableKinds        = ["taxonomy", "taxonomyTerm"]

[params]

  [params.font]
  name = "Open Sans"
  sizes = [400.0, 600.0]

  [params.hero]
  title                     = "KlueLess.io <br/> Static App Factory"
  subtitle                  = "How does a startup build a $million app on a tiny budget in a weekend. <br /> <br />How can an enterprise harness agile / startup methodolies while maintaining quality.<br /> "
  buttontext                = "Get started"
  buttonlink                = "/get-started"
  image                     = "illustrations/worker.svg"

  # clientlogos = ["systek", "tribe", "kromo", "infinite", "gutwork"]

  # Need a menu construction structure
  [params.sidebar]
  logo                      = "fresh-square"

    [[params.sidebar.sections]]
    title                   = "App Generator"
    icon                    = "cogs"

      [[params.sidebar.sections.links]]
      text                  = "Generate"
      url                   = "/generate"

    [[params.sidebar.sections]]
    title                   = "Configuration"
    icon                    = "cog"

      [[params.sidebar.sections.links]]
      text                  = "DDD Models"
      url                   = "/model"

      [[params.sidebar.sections.links]]
      text                  = "Golden Templates"
      url                   = "/template"

      [[params.sidebar.sections.links]]
      text                  = "Profiles"
      url                   = "/profile"

    # [[params.sidebar.sections]]
    # title                   = "Configurations"
    # icon                    = "envelope"

    #   [[params.sidebar.sections.links]]
    #   text                  = "Inbox"
    #   url                   = "/"

    #   [[params.sidebar.sections.links]]
    #   text                  = "Compose"
    #   url                   = "/"

    # [[params.sidebar.sections]]
    # title                   = "Images"
    # icon                    = "image"

    #   [[params.sidebar.sections.links]]
    #   text                  = "Library"
    #   url                   = "/"

    #   [[params.sidebar.sections.links]]
    #   text                  = "Upload"
    #   url                   = "/"


    #   [[params.sidebar.sections.links]]
    #   text                  = "User settings"
    #   url                   = "/"

    #   [[params.sidebar.sections.links]]
    #   text                  = "App settings"
    #   url                   = "/"

  [params.section1]
  title                     = "Great power comes"
  subtitle                  = "with great responsibility"

    [[params.section1.tiles]]
    title                   = "CTO"
    icon                    = "mouse-globe"
    text                    = "Your App must go to market in 30 days and maintain quality and scalability"
    url                     = "/cto"
    buttonText              = "Learn More"

    [[params.section1.tiles]]
    title                   = "Software Architect"
    icon                    = "laptop-cloud"
    text                    = "Design, model and generate Micro Services / Micro Apps with flexible code stacks"
    url                     = "/architect"
    buttonText              = "Learn More"

    [[params.section1.tiles]]
    title                   = "Fullstack Development"
    icon                    = "plug-cloud"
    text                    = "Build Micro Services / Micro Apps and link and connect in language of choice"
    url                     = "/fullstack"
    buttonText              = "Get started"

  [params.section2]
  title                     = "You're looking to build enterprise applications"
  subtitle                  = "Quality / Testibility / Flexibility"

    [[params.section2.features]]
    title                   = "Starter Applications on Steriods"
    text                    = "Why use simple boiler plates when you can get fully configured applications up and run in minutes with database, ci/unit testing and git versioning"
    icon                    = "laptop-globe"

      #  ,  of As the founder or CTO of a startup, you are KlueLess.IO is a software factory that uses Domain Driven Design to build Headless and Serverless applications. <br/> <br/> Software Architects & Lead Developers can develop pilot Full-Stack applications in hours with full unit test coverage up and ruuning.
  # Flexibility through Microservices, enterprise quality through BDD/CI, stack agonostic through Golden Templates. <br /></br />
  # subtitle                  = "KlueLess.IO is a software factory that uses Domain Driven Design to build Headless and Serverless applications. <br/> <br/> Software Architects & Lead Developers can develop pilot Full-Stack applications in hours with full unit test coverage up and ruuning."
# using Domain Driven Design
# Use your 'Golden Templates' 
#  static application generator 

    [[params.section2.features]]
    title                   = "Build a Micro Service / App in a day"
    text                    = "Using domain driven design principals, you build n-tier applications siloed into micro-services and micro-apps with flexibilty to create headless, serverless or fullstack applications"
    icon                    = "doc-sync"
                            
    [[params.section2.features]]
    title                   = "Nomad system"
    text                    = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis."
    icon                    = "mobile-feed"
                            
  [params.section3]
  title                     = "Techology Agnostic"
  subtitle                  = "With DDD modeling and 'Golden Templates', you can pick your frontend/backend language"
  image                     = "illustrations/mockups/app-mockup.png"
  buttonText                = "Get started"
  buttonLink                = "#"

  [params.section4]
  title                     = "Our Clients love us!"
  subtitle                  = "Lorem ipsum sit dolor amet is a dummy text used by typography industry"

    [[params.section4.clients]]
    name                    = "Irma Walters"
    quote                   = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
    job                     = "Accountant"
    img                     = 1.0

    [[params.section4.clients]]
    name                    = "John Bradley"
    quote                   = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
    job                     = "Financial Analyst"
    img                     = 2.0

    [[params.section4.clients]]
    name                    = "Gary Blackman"
    quote                   = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
    job                     = "HR Manager"
    img                     = 3.0

  [params.footer]
  logo = "fresh-white-alt.svg"
  bulmalogo = false

    [[params.footer.socialmedia]]
      active            = false
      icon              = "facebook"
      link              = "https://www.facebook.com/klueless"

    [[params.footer.socialmedia]]
      active            = true
      icon              = "twitter"
      link              = "https://www.twitter.com/liifetourist"

    [[params.footer.socialmedia]]
      active            = false
      icon              = "instagram"
      link              = "https://www.instagram.com/klueless"

    [[params.footer.socialmedia]]
      active            = false
      icon              = "google-plus"
      link              = "https://plus.google.com/+klueless"

    [[params.footer.socialmedia]]
      active            = false
      icon              = "pinterest"
      link              = "https://www.pinterest.com/klueless"

    [[params.footer.socialmedia]]
      active            = true
      icon              = "github"
      link              = "https://github.com/klueless-io"

    [[params.footer.socialmedia]]
      active            = true
      icon              = "envelope-o"
      link              = "mailto://david+klue@ideasmen.com.au"

    [[params.footer.product]]
    text                    = "Discover features"
    link                    = "/"
                            
    [[params.footer.product]]
    text                    = "Why choose our product?"
    link                    = "/"
                            
    [[params.footer.product]]
    text                    = "Compare features"
    link                    = "/"
                            
    [[params.footer.product]]
    text                    = "Our roadmap"
    link                    = "/"
                            
    [[params.footer.product]]
    text                    = "Request features"
    link                    = "/"
                            
    [[params.footer.docs]]
    text                    = "Get started"
    link                    = "/"
                            
    [[params.footer.docs]]
    text                    = "User guides"
    link                    = "/"
                            
    [[params.footer.docs]]
    text                    = "Admin guide"
    link                    = "/"
                            
    [[params.footer.docs]]
    text                    = "Developers"
    link                    = "/"
                            
    [[params.footer.blogroll]]
    text                    = "Latest news"
    link                    = "/"
                            
    [[params.footer.blogroll]]
    text                    = "Tech articles"
    link                    = "/"
                            
    [[params.footer.blogroll]]
    text                    = "Video blog"
    link                    = "/"

  [[params.navbar]]
  title                     = "Features"
  url                       = "/"

  # [[params.navbar]]
  # title                     = "Pricing"
  # url                       = "/"

  [[params.navbar]]
  title = "Dropdown"

    [[params.navbar.sublinks]]
    title                   = "Dropdown item"
    url                     = "/"

    [[params.navbar.sublinks]]
    title                   = "Dropdown item"
    url                     = "/"

    [[params.navbar.sublinks]]
    title                   = "Dropdown item"
    url                     = "/"

  [[params.navbar]]
  title                     = "Log in"
  url                       = "/"

  [[params.navbar]]
  title                     = "Sign up"
  url                       = "/"
  button                    = true